import { startServer, launchBrowser, URL_BASE } from './lib.mjs';
const stop = await startServer();
const b = await launchBrowser();
const ctx = await b.newContext({ viewport: { width: 640, height: 400 } });
const p = await ctx.newPage();
p.on('console', m => console.log(`[${m.type()}]`, m.text().slice(0, 500)));
p.on('pageerror', e => console.log('[PAGEERROR]', String(e).slice(0, 1200)));
await p.goto(`${URL_BASE}/?det=1&seed=1337`, { waitUntil: 'load' });
await new Promise(r => setTimeout(r, 5000));
console.log('ready =', await p.evaluate(() => !!window.__ringfall && window.__ringfall.ready));
await b.close(); await stop(); process.exit(0);
